name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: simple-curl
        run: |
          curl --verbose \
          "https://graph.instagram.com/me/media?fields=media_url,permalink&access_token=${{secrets.IG_ACCESS_TOKEN}}"
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: npm-install
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> .npmrc
          npm install
      - name: test
        run: npm test
      - name: fetch-feed
        id: feed
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: npm run ig-media
      - name: fetch-gh-contributions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run gh-contributions
      - name: upload-feeds
        uses: actions/upload-artifact@v2
        with:
          name: pr-feeds
          path: |
            github-contributions.json
            instagram-media.json
            *.jpg
          retention-days: 1

  ensure-expected-artifacts:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: pr-feeds
          path: pr-feeds
      - name: ensure-json
        run: |
          cat pr-feeds/instagram-media.json
          cat pr-feeds/github-contributions.json
      - name: ensure-images
        run: ls pr-feeds | grep '.jpg'
