name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm-install
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> .npmrc
          npm install
      - name: test
        run: npm test
      - name: fetch-json
        id: feed
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: npm start
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ig-pr
          path: |
            media.json
            *.jpg
          retention-days: 1

  ensure-expected-artifacts:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: ig-pr
          path: ig-pr
      - name: ensure-json
        run: cat ig-pr/media.json
      - name: ensure-images
        run: ls ig-pr | grep *.jpg
