name: generate-ig-feed

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    name: generate-feed
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm-install
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> .npmrc
          npm install
      - name: test
        run: npm test
      - name: fetch-feed
        id: feed
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: npm start
      - name: upload-feed
        uses: actions/upload-artifact@v2
        with:
          name: ig
          path: |
            media.json
            *.jpg
          retention-days: 1

  publish-feed-to-gh-pages:
    needs: generate-feed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: download-feed
        uses: actions/download-artifact@v2
        with:
          name: ig
          path: ig
      - name: publish-feed-to-gh-pages
        uses: mikeal/publish-to-github-action@923d6a6f64c943c0f82f81180c4a84d8e0edaa3e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: gh-pages
