name: generate-feeds

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  generate-feeds:
    runs-on: ubuntu-latest
    name: generate-feed
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: npm-install
        run: npm install
      - name: test
        run: npm test
      - name: fetch-ig-media
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: npm run ig-media
      - name: fetch-gh-contributions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run gh-contributions
      - name: upload-feeds
        uses: actions/upload-artifact@v4
        with:
          name: feeds
          path: |
            github-contributions.json
            instagram-media.json
            instagram-media-*.json
            *.jpg
          retention-days: 1

  publish-feeds-to-gh-pages:
    needs: generate-feeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: gh-pages
      - name: download-feed
        uses: actions/download-artifact@v4
        with:
          name: feeds
          path: feeds
      - name: publish-feeds-to-gh-pages
        uses: mikeal/publish-to-github-action@923d6a6f64c943c0f82f81180c4a84d8e0edaa3e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: gh-pages
