name: RSS

on: [push]
  #schedule:
  #  - cron: "0 17 * * *"

jobs:
  generate_rss:
    runs-on: ubuntu-latest
    name: Generate RSS
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: RSS
        id: rss
        uses: katydecorah/instagram-rss-action@0.1.0
        with:
          yourInstagram: clapclapexcitement
          listOfInstagrams: clapclapexcitement
      - name: Commit files
        if: ${{ success() && steps.rss.outputs.RSS_STATUS == 'success' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "Updated instagram.json"
          git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF}
