name: refresh-ig-access-token

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    name: refresh-ig-token
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
      - name: npm-install
        run: npm install
      - name: refresh-ig-token
        id: refresh-ig-token
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: npm run refresh-ig-token
      - name: update-gh-secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: IG_ACCESS_TOKEN
          value: ${{ steps.refresh-ig-token.outputs.ig-access-token }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: test-updated-gh-secret
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: |
          curl \
            --verbose \
            --location \
            --fail-with-body \
            "https://graph.instagram.com/v21.0/28395689843380207/media?fields=media_url,caption,permalink&access_token=$IG_ACCESS_TOKEN"
