name: refresh-ig-access-token

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    name: refresh-token
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: npm-install
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> .npmrc
          npm install
      - name: refresh-ig-access-token
        id: instagram
        uses: ./node_modules/@saulhardman/refresh-instagram-access-token
        with:
          access_token: ${{ secrets.IG_ACCESS_TOKEN }}
      - name: update-gh-secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: IG_ACCESS_TOKEN
          value: ${{ steps.instagram.outputs.access_token }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
