name: refresh-ig-access-token

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    name: refresh-token
    steps:
      - uses: actions/checkout@v2
      - name: npm-install
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${PERSONAL_ACCESS_TOKEN}" > .npmrc
          npm install
      - name: refresh-ig-access-token
        id: instagram
        uses: ./node_modules/@saulhardman/refresh-instagram-access-token
        with:
          access_token: ${{ secrets.IG_ACCESS_TOKEN }}
      - name: update-gh-secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: NEW_IG_TOKEN
          value: ${{ steps.instagram.outputs.access_token }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
