name: test-ig-token

on:
  workflow_dispatch:

jobs:
  test-ig-token:
    runs-on: ubuntu-latest
    name: test-ig-token
    steps:
      - name: Test token
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: |
          curl \
            --verbose \
            --location \
            "https://graph.instagram.com/me/media?fields=media_url,permalink&access_token=$IG_ACCESS_TOKEN"
